protected/admin/controllers/PublicController.php
<?php
class PublicController extends Controller{
	public $layout=null;
	public $defaultAction='login';
	
	/**
	 * 登入动作
	 */
	public function actionlogin(){
		if(!Yii::app()->user->isGuest){
			$this->redirect(array('site/index'));
		}
		$model=new LoginForm();
		$this->renderPartial('login',array(
				'model'=>$model,
		),$return=false,$processOutput=true);
	}
	
	/**
	 * checklogin
	 * 
	 */
	public function actionCheckLogin(){
		$model=new LoginForm();
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			if($model->validate() && $model->login()){
				//更新登入时间
				$user=Admin::model()->findByPk(yii::app()->user->id);
				$user->login_time=time();
				//save
				$user->save();
				$this->redirect(Yii::app()->request->urlReferrer);
			}else{
				exit('登入失败!');
			}
		}else{
			$this->error('错误的请求',$this->createUrl('site/index'));
		}
	}
	
	/**
	 * 退出
	 */
	public function actionLogout(){
		Yii::app()->user->logout();
		$this->redirect($this->createUrl('public/login'));
	}
	
	
	
	
	/**
	 * 错误捕获
	 */
	public function actionError(){
		if($error=Yii::app()->errorHandler->error){
	
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

?>

protected/admin/controllers/QuestionController.php
<?php
/**
 * 管理问题
 * @author silenceper
 *
 */
class QuestionController extends BaseController {
	/**
	 * 显示问题列表
	 */
	public function actionIndex(){


		$sql="select `{{question}}`.`id`,`{{question}}`.`question_content`,`{{question}}`.`add_time`,`{{question}}`.`update_time`,`{{question}}`.`answer_count`,`{{question}}`.`view_count`,`{{question}}`.`lock`,`{{question}}`.`focus_count`,`{{question}}`.`comment_count`,`{{question}}`.`best_answer`,`{{question}}`.`ip`,`{{users}}`.`username`,`{{users}}`.`uid`
				from `{{question}}`				
				left join `{{users}}` on (`{{users}}`.`uid` = `{{question}}`.`published_uid`)";

		$condition=array();
		//根据uid搜索
		if(isset($_GET['uid'])){
			$condition[]="`{{users}}`.`uid`={$_GET['uid']} ";
		}

		if(isset($_POST['content'])){
			$condition[]=" `{{question}}`.`question_content` like '%{$_POST['content']}%'";
		}

		$conditions=implode('AND', $condition);
		//var_dump($conditions);
		if($conditions){
			$conditions=' where '.$conditions;
			$sql.=$conditions;
		}
		$sql.=" order by `{{question}}`.`add_time` desc ";
		$connection=Yii::app()->db;
		$criteria = new CDbCriteria;
		$models=$connection->createCommand($sql)->queryAll();
		$count=count($models);
		$pages = new CPagination($count);
		$pages->pageSize = 12;
		$pages->applylimit($criteria);
		$models=$connection->createCommand($sql." LIMIT :offset,:limit");
		$models->bindValue(':offset', $pages->currentPage*$pages->pageSize);
		$models->bindValue(':limit', $pages->pageSize);
		$models=$models->queryAll();
		$this->render('index',array(
				'models'=>$models,
				'pages'=>$pages,
				'count'=>$count,
		));
	}
	
	
	/**
	 * 
	 * 更新question中的信息
	 *
	 */
	public function actionUpdate($id){
		$sql="select `{{question}}`.`id`,`{{question}}`.`question_content`,`{{question}}`.`question_detail`,`{{question}}`.`add_time`,`{{question}}`.`update_time`,`{{question}}`.`published_uid`,`{{question}}`.`answer_count`,`{{question}}`.`view_count`,`{{question}}`.`focus_count`,`{{question}}`.`comment_count`,`{{question}}`.`best_answer`,`{{question}}`.`lock`,`{{question}}`.`ip`,`{{users}}`.`username` from `{{question}}` left join `{{users}}` on (`{{users}}`.`uid`=`{{question}}`.`published_uid`) where `{{question}}`.`id`=:id";
		$model=Yii::app()->db->createCommand($sql)->queryRow(true,array(':id'=>$id));
		$this->render('update',array(
				'model'=>$model,
			));
	}

	/**
	 *
	 * 处理更新 
	 *
	 */
	public function actionCheckUpdate(){
		if (!isset($_POST)) {
			$this->error('错误的访问方式');
		}

		//开始处理提交信息
		//var_dump($_POST);
		$m=Question::model()->updateByPk($_POST['id'],array(
			'question_content'=>htmlspecialchars($_POST['question_content']),
			'question_detail'=>htmlspecialchars($_POST['question_detail']),
			'lock'=>$_POST['lock'],
			'update_time'=>time(),
			));
		if(false!==$m){
			$this->error('更新成功');
		}

	}


	/**
	 * 删除信息
	 * 多表删除  事物处理
	 * 删除 question 中信息
	 * 删除 answer 表中信息
	 * 删除 question 
	 * 更新topic中次数
	 */
	public function actionDelete($id){		
		$transaction=Yii::app()->db->beginTransaction();
		try {
			
			//删除question 表信息
			if(!Question::model()->deleteByPk($id)){
				throw new Exception("删除question表失败");
			}

			//删除 topic_question 表 首先把 topic  id 查找出来
			//获取topic id
			$topic_ids=TopicQuestion::model()->findAll(array(
					'select'=>'topic_id',
					'condition'=>'question_id=:question_id',
					'params'=>array(':question_id'=>$id),
				));

			//更新 topic次数
			foreach ($topic_ids as $model) {
				//更新topic 次数
				if(!Topic::model()->updateByPk($model->topic_id, array('discuss_count'=>new CDbExpression('discuss_count-1')))){
					throw new ErrorException('更新失败');
				}
			}

			//删除topic_question 表中信息
			if(false === TopicQuestion::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除topic_question中信息失败');
			}

			//删除question_comment 中信息
			if(false === QuestionComments::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除question_comment中信息失败');
			}

			//获取answer_comment 中id
			$answer_comment_models=Answer::model()->findAll(array(
					'select'=>'id',
					'condition'=>'question_id=:question_id',
					'params'=>array(
						':question_id'=>$id,
						),
				));

			//删除answer_comment 中信息
			foreach ($answer_comment_models as $answer_comment_model) {
				if(false === AnswerComments::model()->deleteAll('answer_id=:answer_id',array(':answer_id'=>$answer_comment_model->id))){
					throw new ErrorException('删除answer_comment中信息失败');
				}
			}

			//删除answer 表中信息
			if(false === Answer::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除answer中信息失败');
			}

			//删除question_focus 中信息
			if(false === QuestionFocus::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除question_focus 中信息失败');
			}

			$transaction->commit();
			$this->success('删除成功');
		}catch(Exception $e){
			$transaction->rollBack();
			exit($e->getMessage());
			$this->error($e->getMessage());
		}

	}
}

?>

protected/admin/controllers/SiteController.php
<?php
/**
 * @author silenceper
 */
class SiteController extends BaseController{
	/**
	 * 显示网站首页
	 */
	public function actionIndex(){
		$this->render('index');
	}

	
	/**
	 * 显示服务器信息
	 */
	public function actionInfo(){
		echo '系统信息！~';
	}
}

?>

protected/admin/controllers/UserController.php
<?php
/**
 *  用户管理
 * @author silenceper
 *
 */

class UserController extends BaseController {
	/*
	 * 显示用户列表
	 */
	public function actionIndex(){
		$sql="select `{{users}}`.`uid`,`{{users}}`.`username`,`{{users}}`.`email`,`{{users}}`.`avatar_file`,`{{users}}`.`sex`,`{{users}}`.`birthday`,`{{users}}`.`reg_time`,`{{users}}`.`reg_ip`,`{{users}}`.`last_login`,`{{users}}`.`last_ip` from `{{users}}`";

		//查找用户
		if(isset($_POST['content'])){
			$sql.=" where `{{users}}`.`username` like '%{$_POST['content']}%'";
		}

		$connection=Yii::app()->db;
		$criteria = new CDbCriteria;
		$models=$connection->createCommand($sql)->queryAll();
		$count=count($models);
		$pages = new CPagination($count);
		$pages->pageSize = 14;
		$pages->applylimit($criteria);
		$models=$connection->createCommand($sql." LIMIT :offset,:limit");
		$models->bindValue(':offset', $pages->currentPage*$pages->pageSize);
		$models->bindValue(':limit', $pages->pageSize);
		$models=$models->queryAll();
		$this->render('index',array(
				'models'=>$models,
				'pages'=>$pages,
				'count'=>$count,
		));
	}	

	/**
	 * 
	 * update
	 */
	public function actionUpdate($uid){
		$model=Users::model()->findByPk($uid);		
		if(!$model){
			$this->error('不存在该用户');
		}

		$this->render('update',array(
				'model'=>$model,
			));
	}

	/**
	 * 
	 * 检查update
	 *
	 */
	public function actionCheckUpdate(){
		if(!Yii::app()->request->isPostRequest){
			$this->error('一定是您的访问方式不对','/');
		}
		//执行更新操作
		//var_dump($_POST);
		$data=array();
		$data['username']=$_POST['username'];
		$data['sex']=$_POST['sex'];
		$data['mobile']=$_POST['mobile'];
		//生日更新  
		$birthday=$_POST['birthday'];
		$year=substr($birthday,0,4);
		$month=substr($birthday,5,2);
		$day=substr($birthday, 8,2);
		$data['birthday']=mktime(0,0,0,$month,$day,$year);
		//密码更新
		if($_POST['password']){
			$data['salt']=Help::fetchSalt();
			$data['password']=md5(md5(trim($_POST['password'])).$data['salt']);	
		}
		
		//更新头像
		$image=Help::uploadAvatar($_POST['uid'],'avatar');
		if($image){
			$data['avatar_file']=$image;
		}

		if(false !== Users::model()->updateByPk($_POST['uid'],$data)){
			$this->success('更新成功',$this->createUrl('index'));
		}
	}

	/**
	 * 添加用户
	 */
	public function actionAdd(){
		$this->render('add');
	}

	/**
	 * 处理添加用户
	 */
	public function actionCheckAdd()
	{	
		if(!Yii::app()->request->isPostRequest){
			$this->error('一定是您的访问方式不对');
		}
		//var_dump($_POST);
		//判断用户名或email是否已经存在
		if(Users::model()->exists('username=? or email=?', array($_POST['username'],$_POST['email']))){
			$this->error('用户名或密码已经存在!');
		}

		//首先插入数据获取uid
		$user=new Users;
		$user->username=$_POST['username'];
		$user->email=$_POST['email'];
		//生日更新  
		$birthday=$_POST['birthday'];
		$year=substr($birthday,0,4);
		$month=substr($birthday,5,2);
		$day=substr($birthday, 8,2);
		$user->birthday=mktime(0,0,0,$month,$day,$year);
		$user->mobile=$_POST['mobile'];
		$user->sex=$_POST['sex'];
		$user->salt=Help::fetchSalt();
		$user->password=md5(md5($_POST['password']).$user->salt);
		$user->reg_time=time();
		$user->reg_ip=Yii::app()->request->userHostAddress;
		$user->last_login=time();
		$user->last_ip=Yii::app()->request->userHostAddress;

		if($user->save()){
			$this->success('添加成功!');
		}else{
			$this->error(var_dump($user->errors));
		}

	}


	/**
	 * 获取提问数
	 */
	public function getQuestionCount($uid){
		return Question::model()->count('published_uid=:uid',array(':uid'=>$uid));
	}

	/**
	 * 获取回答数
	 */
	public function getAnswerCount($uid){
		return Answer::model()->count('uid=:uid',array(':uid'=>$uid));
	}

}

?>

protected/admin/views/site/flash.php
<meta  http-equiv="refresh" content="<?php echo $time;?>;url=<?php echo $url;?>" />
<?php
	$this->pageTitle=$mesg;
?>
<div style="text-align:center;margin-top:20px;">
	<h4><?php echo CHtml::encode($mesg); ?></h4>
	
	<div class="error">
		<?php echo $time?>秒钟后跳转~
	</div>
</div>

protected/admin/views/site/index.php
<div class="navbar navbar-static-top navbar-inverse">
        	<div class="navbar-inner">
            	<div style="padding:0 30px;">
                	<a href="/" class="brand" style="margin-right:20px;">ASK后台管理</a>
                	<div class="nav-collapse collapse navbar-inverse-collapse">
                        <!--  用户名头像下拉 -->
                        <ul class="nav pull-right">
                        <?php 
                        	//用户已经登入
                        	if(!Yii::app()->user->isGuest):
                        ?>	
                        	<li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <span style="color:white;"><?php echo Yii::app()->user->getState('userInfo')->username; ?></span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                    <li>
                                        <a href="<?php echo $this->createUrl('public/logout')?>"><i class="icon-off"></i>退出</a>
                                    </li>
                                </ul>
                            </li>
                            <?php 
                            	endif;
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<div class="row" >
	<div class="span3" style="min-height:600px;background-color: #e9e9e9;border-right: 1px solid #c4c8cb;">
	<div class="sidebar-menu">
		<a href="#questionMenu" class="nav-header menu-first collapsed" data-toggle="collapse"><i class="icon-book icon-large"></i> 问题管理</a>
		<ul id="questionMenu" class="nav nav-list collapse menu-second">
			<li><a href="<?php echo $this->createUrl('question/index');?>" target="main"><i class="icon-list-alt"></i> 问题列表</a></li>
		</ul>
		
		<!-- <a href="#topicMeun" class="nav-header menu-first collapsed" data-toggle="collapse"><i class="icon-tag icon-large"></i> 话题管理</a>
		<ul id="topicMeun" class="nav nav-list collapse menu-second">
			<li><a href="#" target="main"><i class="icon-list-alt"></i> 所有话题</a></li>
		</ul>
		 -->
		<a href="#userMeun" class="nav-header menu-first collapsed" data-toggle="collapse"><i class="icon-user icon-large"></i> 用户管理</a>
		<ul id="userMeun" class="nav nav-list collapse menu-second">
            <li><a href="<?php echo $this->createUrl('user/index'); ?>" target="main"><i class="icon-list"></i> 用户列表</a></li>
			<li><a href="<?php echo $this->createUrl('user/add'); ?>" target="main"><i class="icon-user"></i> 增加用户</a></li>
		</ul>
		
	</div>
</div>

<!-- iframe -->
<div class="right_main"  style="position:relative; overflow:hidden;">
	  <iframe name="main" id="rightMain" src="<?php echo $this->createUrl('site/info')?>"  frameborder="false" scrolling="auto" style="overflow-x:hidden;border:none;" width="100%" allowtransparency="true" height:200></iframe>
	</div>
</div>
<script type="text/javascript">function windowW(){
	if($(window).width()<980){

			$('#header').css('width',980+'px');

			$('#content').css('width',980+'px');

			$('body').attr('scroll','');

			$('body').css('overflow','');
	}

}

windowW();

$(window).resize(function(){

	if($(window).width()<980){

		windowW();

	}else{

		$('#header').css('width','auto');

		$('#content').css('width','auto');

		$('body').attr('scroll','no');

		$('body').css('overflow','hidden');

	}

});

window.onresize = function(){

	var heights = document.documentElement.clientHeight;

	document.getElementById('rightMain').height = heights;

	var openClose = $("#rightMain").height()+9;

	$('#center_frame').height(openClose+9);

	$("#openClose").height(openClose+30);

}

window.onresize();
</script>