protected/admin/controllers/QuestionController.php
<?php
/**
 * 管理问题
 * @author silenceper
 *
 */
class QuestionController extends BaseController {
	/**
	 * 显示问题列表
	 */
	public function actionIndex(){


		$sql="select `{{question}}`.`id`,`{{question}}`.`question_content`,`{{question}}`.`add_time`,`{{question}}`.`update_time`,`{{question}}`.`answer_count`,`{{question}}`.`view_count`,`{{question}}`.`lock`,`{{question}}`.`focus_count`,`{{question}}`.`comment_count`,`{{question}}`.`best_answer`,`{{question}}`.`ip`,`{{users}}`.`username`,`{{users}}`.`uid`
				from `{{question}}`				
				left join `{{users}}` on (`{{users}}`.`uid` = `{{question}}`.`published_uid`)";

		$condition=array();
		//根据uid搜索
		if(isset($_GET['uid'])){
			$condition[]="`{{users}}`.`uid`={$_GET['uid']} ";
		}

		if(isset($_POST['content'])){
			$condition[]=" `{{question}}`.`question_content` like '%{$_POST['content']}%'";
		}

		$conditions=implode('AND', $condition);
		//var_dump($conditions);
		if($conditions){
			$conditions=' where '.$conditions;
			$sql.=$conditions;
		}
		$sql.=" order by `{{question}}`.`add_time` desc ";
		$connection=Yii::app()->db;
		$criteria = new CDbCriteria;
		$models=$connection->createCommand($sql)->queryAll();
		$count=count($models);
		$pages = new CPagination($count);
		$pages->pageSize = 12;
		$pages->applylimit($criteria);
		$models=$connection->createCommand($sql." LIMIT :offset,:limit");
		$models->bindValue(':offset', $pages->currentPage*$pages->pageSize);
		$models->bindValue(':limit', $pages->pageSize);
		$models=$models->queryAll();
		$this->render('index',array(
				'models'=>$models,
				'pages'=>$pages,
				'count'=>$count,
		));
	}
	
	
	/**
	 * 
	 * 更新question中的信息
	 *
	 */
	public function actionUpdate($id){
		$sql="select `{{question}}`.`id`,`{{question}}`.`question_content`,`{{question}}`.`question_detail`,`{{question}}`.`add_time`,`{{question}}`.`update_time`,`{{question}}`.`published_uid`,`{{question}}`.`answer_count`,`{{question}}`.`view_count`,`{{question}}`.`focus_count`,`{{question}}`.`comment_count`,`{{question}}`.`best_answer`,`{{question}}`.`lock`,`{{question}}`.`ip`,`{{users}}`.`username` from `{{question}}` left join `{{users}}` on (`{{users}}`.`uid`=`{{question}}`.`published_uid`) where `{{question}}`.`id`=:id";
		$model=Yii::app()->db->createCommand($sql)->queryRow(true,array(':id'=>$id));
		$this->render('update',array(
				'model'=>$model,
			));
	}

	/**
	 *
	 * 处理更新 
	 *
	 */
	public function actionCheckUpdate(){
		if (!isset($_POST)) {
			$this->error('错误的访问方式');
		}

		//开始处理提交信息
		//var_dump($_POST);
		$m=Question::model()->updateByPk($_POST['id'],array(
			'question_content'=>htmlspecialchars($_POST['question_content']),
			'question_detail'=>htmlspecialchars($_POST['question_detail']),
			'lock'=>$_POST['lock'],
			'update_time'=>time(),
			));
		if(false!==$m){
			$this->error('更新成功');
		}

	}


	/**
	 * 删除信息
	 * 多表删除  事物处理
	 * 删除 question 中信息
	 * 删除 answer 表中信息
	 * 删除 question 
	 * 更新topic中次数
	 */
	public function actionDelete($id){		
		$transaction=Yii::app()->db->beginTransaction();
		try {
			
			//删除question 表信息
			if(!Question::model()->deleteByPk($id)){
				throw new Exception("删除question表失败");
			}

			//删除 topic_question 表 首先把 topic  id 查找出来
			//获取topic id
			$topic_ids=TopicQuestion::model()->findAll(array(
					'select'=>'topic_id',
					'condition'=>'question_id=:question_id',
					'params'=>array(':question_id'=>$id),
				));

			//更新 topic次数
			foreach ($topic_ids as $model) {
				//更新topic 次数
				if(!Topic::model()->updateByPk($model->topic_id, array('discuss_count'=>new CDbExpression('discuss_count-1')))){
					throw new ErrorException('更新失败');
				}
			}

			//删除topic_question 表中信息
			if(false === TopicQuestion::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除topic_question中信息失败');
			}

			//删除question_comment 中信息
			if(false === QuestionComments::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除question_comment中信息失败');
			}

			//获取answer_comment 中id
			$answer_comment_models=Answer::model()->findAll(array(
					'select'=>'id',
					'condition'=>'question_id=:question_id',
					'params'=>array(
						':question_id'=>$id,
						),
				));

			//删除answer_comment 中信息
			foreach ($answer_comment_models as $answer_comment_model) {
				if(false === AnswerComments::model()->deleteAll('answer_id=:answer_id',array(':answer_id'=>$answer_comment_model->id))){
					throw new ErrorException('删除answer_comment中信息失败');
				}
			}

			//删除answer 表中信息
			if(false === Answer::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除answer中信息失败');
			}

			//删除question_focus 中信息
			if(false === QuestionFocus::model()->deleteAll('question_id=:question_id',array('question_id'=>$id))){
				throw new ErrorException('删除question_focus 中信息失败');
			}

			$transaction->commit();
			$this->success('删除成功');
		}catch(Exception $e){
			$transaction->rollBack();
			exit($e->getMessage());
			$this->error($e->getMessage());
		}

	}
}

?>

protected/admin/views/question/index.php
<div class="condition alert alert-info">
	<?php $form = $this->beginWidget('CActiveForm', array(
	    'id'=>'condition-form',
	    'enableAjaxValidation'=>true,
	    'enableClientValidation'=>true,
	    'htmlOptions'=>array('class'=>'form-horizontal'),
	)); ?>
	搜索关键字:<input type="text" name="content"/>	
	<input type="submit" value="查询" class="btn btn-info">
	<span class="text-error">共有 <?php echo $count; ?>个问题</span>
	<?php $this->endWidget(); ?>

</div>
<!-- 显示列表 -->
<div class="content">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>标题</th>
				<th>作者</th>
				<th>时间</th>
				<th>回复数</th>
				<th>关注数</th>
				<th>评论数</th>
				<th>浏览数</th>
				<th>状态</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($models as $model):?>
			<?php 
				$status='';
				if($model['best_answer']){
					$status='success';
				}elseif($model['lock']){
					$status='error';
				}
			 ?>

			<tr class="<?php echo $status; ?>">
				<td><?php echo $model['id']?></td>		
				<td><a href="/question/index?id=<?php echo $model['id'] ?>" target="_blank"><?php echo $model['question_content']?></a></td>		
				<td><a href="
					<?php echo $this->createUrl('question/index',array('uid'=>$model['uid'])); ?>"><?php echo $model['username']?></a></td>	
				<td><?php echo date('Y-m-d H:i:s',$model['add_time'])?></td>		
				<td><?php echo $model['answer_count']?></td>		
				<td><?php echo $model['focus_count']?></td>		
				<td><?php echo $model['comment_count']?></td>		
				<td><?php echo $model['view_count']?></td>	
				<td><?php  echo ($model['lock']==1) ?  '<span class="text-error">锁定</span>': '正常';?></td>		
				<td>
					<a href="<?php echo $this->createUrl('question/update',array('id'=>$model['id'])); ?>">编辑</a> &nbsp; / &nbsp;
					<a href="<?php echo $this->createUrl('question/delete',array('id'=>$model['id'])); ?>" class="text-error" onclick="return confirm('您确认要删除吗，删除之后将无法恢复?')">删除</a> 
				</td>
			</tr>
		<?php endforeach;?>
			<tr>
			<td colspan="10" style="text-align:center;">
				<?php 
                  //分页
                  $this->widget('CLinkPager', array(
						 'header'=>'',
						 'pages' => $pages,
					));
		 		 ?>
		 	</td>
			</tr>
		</tbody>
	</table>
</div>

protected/admin/views/question/update.php
<?php 
	$this->pageTitle="更新";	
	$form=$this->beginWidget('CActiveForm',array(
				'action'=>$this->createUrl('question/checkupdate'),
				'id'=>'update-form',
			));
?>
<div class="content">
	<table class="table table-striped table-bordered" id="update">
		<tr>
			<th class="text-right">标题：</th>
			<td>
				<input type="text" name="question_content" value="<?php echo $model['question_content'] ?>" />
				<?php if($model['best_answer']): ?>
					<span class="label label-success">已解决</span>
				<?php endif; ?>
				<?php if($model['lock']): ?>
					<span class="label label-important">已锁定</span>
				<?php endif; ?>
			</td>		
		</tr>
		<tr>
			<th class="text-right">作者：</th>
			<td><a target="_blank" href="/question/index?id=<?php echo $model['id'] ?>" ><?php echo $model['username'] ?></a></td>		
		</tr>
		<tr>
			<th class="text-right">详细：</th>
			<td><textarea name="question_detail"><?php echo  $model['question_detail'] ;?></textarea></td>		
		</tr>
		<tr>
			<th>锁定</th>
			<td>
				<select name='lock'>
					<option value="0" <?php if($model['lock']==0)echo 'selected' ?> >正常</option>
					<option value="1" <?php if($model['lock']==1)echo 'selected' ?> >锁定</option>
				</select>
			</td>
		</tr>
		<tr>
			<th>状态:</th>
			<td id="status">
				<span class="label label-info"><?php echo $model['view_count'] ?>人查看</span>
				<span class="label label-info"><?php echo $model['focus_count'] ?>人关注</span>
				<span class="label label-info"><?php echo $model['answer_count'] ?>人回答</span>
				<span class="label label-info"><?php echo $model['comment_count'] ?>人评论</span>
			</td>
		</tr>
		<tr>
			<th>时间:</th>
			<td>
				<p>发布时间:<?php echo date('Y-m-d H:i:s',$model['add_time']); ?></p>
				<p>最后更新时间:<?php echo date('Y-m-d H:i:s',$model['update_time']); ?></p>	
			</td>
		</tr>
		<tr>	
			<td></td>
			<td>
				<input type="hidden" name="id" value="<?php echo $model['id'] ?>">
				<input type="submit" value="保存" class="btn btn-primary">
				<a href="javascript:window.history.back(-1)" class="btn">返回</a>
			</td>
		</tr>
	</table>
	<?php 
		$this->endWidget();
	 ?>
</div>	